browsers:
  - name: chrome
    version: latest
  - name: ie
    version: '10,11,latest'
  - name: firefox
    version: 25..latest
    platform: 'Linux'
  - name: safari
    version: 5..latest
  - name: iphone
    version: '8,9,10,latest'
  - name: android
    version: ..latest